# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class FBMonster(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFBMonster(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FBMonster()
        x.Init(buf, n + offset)
        return x

    # FBMonster
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FBMonster
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # FBMonster
    def Hp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # FBMonster
    def Attack(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def FBMonsterStart(builder): builder.StartObject(3)
def FBMonsterAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def FBMonsterAddHp(builder, hp): builder.PrependInt32Slot(1, hp, 0)
def FBMonsterAddAttack(builder, attack): builder.PrependInt32Slot(2, attack, 0)
def FBMonsterEnd(builder): return builder.EndObject()
