# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class TShowConditionConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTShowConditionConfig(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TShowConditionConfig()
        x.Init(buf, n + offset)
        return x

    # TShowConditionConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TShowConditionConfig
    def Datalist(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .TShowConditionConfigRowData import TShowConditionConfigRowData
            obj = TShowConditionConfigRowData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TShowConditionConfig
    def DatalistLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def TShowConditionConfigStart(builder): builder.StartObject(1)
def TShowConditionConfigAddDatalist(builder, datalist): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(datalist), 0)
def TShowConditionConfigStartDatalistVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TShowConditionConfigEnd(builder): return builder.EndObject()
