# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class TShowMusicsConfig(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTShowMusicsConfig(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TShowMusicsConfig()
        x.Init(buf, n + offset)
        return x

    # TShowMusicsConfig
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TShowMusicsConfig
    def Datalist(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .TShowMusicsConfigRowData import TShowMusicsConfigRowData
            obj = TShowMusicsConfigRowData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # TShowMusicsConfig
    def DatalistLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def TShowMusicsConfigStart(builder): builder.StartObject(1)
def TShowMusicsConfigAddDatalist(builder, datalist): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(datalist), 0)
def TShowMusicsConfigStartDatalistVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TShowMusicsConfigEnd(builder): return builder.EndObject()
