// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

pub enum TShowConditionConfigRowDataOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct TShowConditionConfigRowData<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TShowConditionConfigRowData<'a> {
    type Inner = TShowConditionConfigRowData<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> TShowConditionConfigRowData<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TShowConditionConfigRowData {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args TShowConditionConfigRowDataArgs<'args>) -> flatbuffers::WIPOffset<TShowConditionConfigRowData<'bldr>> {
      let mut builder = TShowConditionConfigRowDataBuilder::new(_fbb);
      if let Some(x) = args.ClothesCondition { builder.add_ClothesCondition(x); }
      builder.add_StyleNum(args.StyleNum);
      builder.add_StyleCondition(args.StyleCondition);
      if let Some(x) = args.EndTime { builder.add_EndTime(x); }
      if let Some(x) = args.OpenTime { builder.add_OpenTime(x); }
      builder.add_ID(args.ID);
      builder.finish()
    }

    pub const VT_ID: flatbuffers::VOffsetT = 4;
    pub const VT_OPENTIME: flatbuffers::VOffsetT = 6;
    pub const VT_ENDTIME: flatbuffers::VOffsetT = 8;
    pub const VT_STYLECONDITION: flatbuffers::VOffsetT = 10;
    pub const VT_STYLENUM: flatbuffers::VOffsetT = 12;
    pub const VT_CLOTHESCONDITION: flatbuffers::VOffsetT = 14;

  #[inline]
  pub fn ID(&self) -> i32 {
    self._tab.get::<i32>(TShowConditionConfigRowData::VT_ID, Some(0)).unwrap()
  }
  #[inline]
  pub fn OpenTime(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TShowConditionConfigRowData::VT_OPENTIME, None)
  }
  #[inline]
  pub fn EndTime(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TShowConditionConfigRowData::VT_ENDTIME, None)
  }
  #[inline]
  pub fn StyleCondition(&self) -> i32 {
    self._tab.get::<i32>(TShowConditionConfigRowData::VT_STYLECONDITION, Some(0)).unwrap()
  }
  #[inline]
  pub fn StyleNum(&self) -> i32 {
    self._tab.get::<i32>(TShowConditionConfigRowData::VT_STYLENUM, Some(0)).unwrap()
  }
  #[inline]
  pub fn ClothesCondition(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TShowConditionConfigRowData::VT_CLOTHESCONDITION, None)
  }
}

pub struct TShowConditionConfigRowDataArgs<'a> {
    pub ID: i32,
    pub OpenTime: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub EndTime: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub StyleCondition: i32,
    pub StyleNum: i32,
    pub ClothesCondition: Option<flatbuffers::WIPOffset<&'a  str>>,
}
impl<'a> Default for TShowConditionConfigRowDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        TShowConditionConfigRowDataArgs {
            ID: 0,
            OpenTime: None,
            EndTime: None,
            StyleCondition: 0,
            StyleNum: 0,
            ClothesCondition: None,
        }
    }
}
pub struct TShowConditionConfigRowDataBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TShowConditionConfigRowDataBuilder<'a, 'b> {
  #[inline]
  pub fn add_ID(&mut self, ID: i32) {
    self.fbb_.push_slot::<i32>(TShowConditionConfigRowData::VT_ID, ID, 0);
  }
  #[inline]
  pub fn add_OpenTime(&mut self, OpenTime: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TShowConditionConfigRowData::VT_OPENTIME, OpenTime);
  }
  #[inline]
  pub fn add_EndTime(&mut self, EndTime: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TShowConditionConfigRowData::VT_ENDTIME, EndTime);
  }
  #[inline]
  pub fn add_StyleCondition(&mut self, StyleCondition: i32) {
    self.fbb_.push_slot::<i32>(TShowConditionConfigRowData::VT_STYLECONDITION, StyleCondition, 0);
  }
  #[inline]
  pub fn add_StyleNum(&mut self, StyleNum: i32) {
    self.fbb_.push_slot::<i32>(TShowConditionConfigRowData::VT_STYLENUM, StyleNum, 0);
  }
  #[inline]
  pub fn add_ClothesCondition(&mut self, ClothesCondition: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TShowConditionConfigRowData::VT_CLOTHESCONDITION, ClothesCondition);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TShowConditionConfigRowDataBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TShowConditionConfigRowDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TShowConditionConfigRowData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum TShowConditionConfigOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct TShowConditionConfig<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TShowConditionConfig<'a> {
    type Inner = TShowConditionConfig<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> TShowConditionConfig<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TShowConditionConfig {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args TShowConditionConfigArgs<'args>) -> flatbuffers::WIPOffset<TShowConditionConfig<'bldr>> {
      let mut builder = TShowConditionConfigBuilder::new(_fbb);
      if let Some(x) = args.datalist { builder.add_datalist(x); }
      builder.finish()
    }

    pub const VT_DATALIST: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn datalist(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TShowConditionConfigRowData<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<flatbuffers::ForwardsUOffset<TShowConditionConfigRowData<'a>>>>>(TShowConditionConfig::VT_DATALIST, None)
  }
}

pub struct TShowConditionConfigArgs<'a> {
    pub datalist: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a , flatbuffers::ForwardsUOffset<TShowConditionConfigRowData<'a >>>>>,
}
impl<'a> Default for TShowConditionConfigArgs<'a> {
    #[inline]
    fn default() -> Self {
        TShowConditionConfigArgs {
            datalist: None,
        }
    }
}
pub struct TShowConditionConfigBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TShowConditionConfigBuilder<'a, 'b> {
  #[inline]
  pub fn add_datalist(&mut self, datalist: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<TShowConditionConfigRowData<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TShowConditionConfig::VT_DATALIST, datalist);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TShowConditionConfigBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TShowConditionConfigBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TShowConditionConfig<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

