// automatically generated by the FlatBuffers compiler, do not modify



use std::mem;
use std::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::EndianScalar;

pub enum TShowMusicsConfigRowDataOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct TShowMusicsConfigRowData<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TShowMusicsConfigRowData<'a> {
    type Inner = TShowMusicsConfigRowData<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> TShowMusicsConfigRowData<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TShowMusicsConfigRowData {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args TShowMusicsConfigRowDataArgs<'args>) -> flatbuffers::WIPOffset<TShowMusicsConfigRowData<'bldr>> {
      let mut builder = TShowMusicsConfigRowDataBuilder::new(_fbb);
      builder.add_TotalTime2(args.TotalTime2);
      builder.add_TotalTime(args.TotalTime);
      if let Some(x) = args.BGMName { builder.add_BGMName(x); }
      if let Some(x) = args.noteName { builder.add_noteName(x); }
      builder.add_iD(args.iD);
      builder.finish()
    }

    pub const VT_ID: flatbuffers::VOffsetT = 4;
    pub const VT_NOTENAME: flatbuffers::VOffsetT = 6;
    pub const VT_BGMNAME: flatbuffers::VOffsetT = 8;
    pub const VT_TOTALTIME: flatbuffers::VOffsetT = 10;
    pub const VT_TOTALTIME2: flatbuffers::VOffsetT = 12;

  #[inline]
  pub fn iD(&self) -> i32 {
    self._tab.get::<i32>(TShowMusicsConfigRowData::VT_ID, Some(0)).unwrap()
  }
  #[inline]
  pub fn noteName(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TShowMusicsConfigRowData::VT_NOTENAME, None)
  }
  #[inline]
  pub fn BGMName(&self) -> Option<&'a str> {
    self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TShowMusicsConfigRowData::VT_BGMNAME, None)
  }
  #[inline]
  pub fn TotalTime(&self) -> i32 {
    self._tab.get::<i32>(TShowMusicsConfigRowData::VT_TOTALTIME, Some(0)).unwrap()
  }
  #[inline]
  pub fn TotalTime2(&self) -> f32 {
    self._tab.get::<f32>(TShowMusicsConfigRowData::VT_TOTALTIME2, Some(0.0)).unwrap()
  }
}

pub struct TShowMusicsConfigRowDataArgs<'a> {
    pub iD: i32,
    pub noteName: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub BGMName: Option<flatbuffers::WIPOffset<&'a  str>>,
    pub TotalTime: i32,
    pub TotalTime2: f32,
}
impl<'a> Default for TShowMusicsConfigRowDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        TShowMusicsConfigRowDataArgs {
            iD: 0,
            noteName: None,
            BGMName: None,
            TotalTime: 0,
            TotalTime2: 0.0,
        }
    }
}
pub struct TShowMusicsConfigRowDataBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TShowMusicsConfigRowDataBuilder<'a, 'b> {
  #[inline]
  pub fn add_iD(&mut self, iD: i32) {
    self.fbb_.push_slot::<i32>(TShowMusicsConfigRowData::VT_ID, iD, 0);
  }
  #[inline]
  pub fn add_noteName(&mut self, noteName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TShowMusicsConfigRowData::VT_NOTENAME, noteName);
  }
  #[inline]
  pub fn add_BGMName(&mut self, BGMName: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TShowMusicsConfigRowData::VT_BGMNAME, BGMName);
  }
  #[inline]
  pub fn add_TotalTime(&mut self, TotalTime: i32) {
    self.fbb_.push_slot::<i32>(TShowMusicsConfigRowData::VT_TOTALTIME, TotalTime, 0);
  }
  #[inline]
  pub fn add_TotalTime2(&mut self, TotalTime2: f32) {
    self.fbb_.push_slot::<f32>(TShowMusicsConfigRowData::VT_TOTALTIME2, TotalTime2, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TShowMusicsConfigRowDataBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TShowMusicsConfigRowDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TShowMusicsConfigRowData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

pub enum TShowMusicsConfigOffset {}
#[derive(Copy, Clone, Debug, PartialEq)]

pub struct TShowMusicsConfig<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TShowMusicsConfig<'a> {
    type Inner = TShowMusicsConfig<'a>;
    #[inline]
    fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table { buf: buf, loc: loc },
        }
    }
}

impl<'a> TShowMusicsConfig<'a> {
    #[inline]
    pub fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TShowMusicsConfig {
            _tab: table,
        }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args TShowMusicsConfigArgs<'args>) -> flatbuffers::WIPOffset<TShowMusicsConfig<'bldr>> {
      let mut builder = TShowMusicsConfigBuilder::new(_fbb);
      if let Some(x) = args.datalist { builder.add_datalist(x); }
      builder.finish()
    }

    pub const VT_DATALIST: flatbuffers::VOffsetT = 4;

  #[inline]
  pub fn datalist(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<TShowMusicsConfigRowData<'a>>>> {
    self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<flatbuffers::ForwardsUOffset<TShowMusicsConfigRowData<'a>>>>>(TShowMusicsConfig::VT_DATALIST, None)
  }
}

pub struct TShowMusicsConfigArgs<'a> {
    pub datalist: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a , flatbuffers::ForwardsUOffset<TShowMusicsConfigRowData<'a >>>>>,
}
impl<'a> Default for TShowMusicsConfigArgs<'a> {
    #[inline]
    fn default() -> Self {
        TShowMusicsConfigArgs {
            datalist: None,
        }
    }
}
pub struct TShowMusicsConfigBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> TShowMusicsConfigBuilder<'a, 'b> {
  #[inline]
  pub fn add_datalist(&mut self, datalist: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<TShowMusicsConfigRowData<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TShowMusicsConfig::VT_DATALIST, datalist);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> TShowMusicsConfigBuilder<'a, 'b> {
    let start = _fbb.start_table();
    TShowMusicsConfigBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TShowMusicsConfig<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

