// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct TShowMusicsConfigRowData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static TShowMusicsConfigRowData GetRootAsTShowMusicsConfigRowData(ByteBuffer _bb) { return GetRootAsTShowMusicsConfigRowData(_bb, new TShowMusicsConfigRowData()); }
  public static TShowMusicsConfigRowData GetRootAsTShowMusicsConfigRowData(ByteBuffer _bb, TShowMusicsConfigRowData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public TShowMusicsConfigRowData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string NoteName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNoteNameBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetNoteNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNoteNameArray() { return __p.__vector_as_array<byte>(6); }
  public string BGMName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBGMNameBytes() { return __p.__vector_as_span(8); }
#else
  public ArraySegment<byte>? GetBGMNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetBGMNameArray() { return __p.__vector_as_array<byte>(8); }
  public int TotalTime { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<TShowMusicsConfigRowData> CreateTShowMusicsConfigRowData(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset NoteNameOffset = default(StringOffset),
      StringOffset BGMNameOffset = default(StringOffset),
      int TotalTime = 0) {
    builder.StartObject(4);
    TShowMusicsConfigRowData.AddTotalTime(builder, TotalTime);
    TShowMusicsConfigRowData.AddBGMName(builder, BGMNameOffset);
    TShowMusicsConfigRowData.AddNoteName(builder, NoteNameOffset);
    TShowMusicsConfigRowData.AddID(builder, ID);
    return TShowMusicsConfigRowData.EndTShowMusicsConfigRowData(builder);
  }

  public static void StartTShowMusicsConfigRowData(FlatBufferBuilder builder) { builder.StartObject(4); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddNoteName(FlatBufferBuilder builder, StringOffset NoteNameOffset) { builder.AddOffset(1, NoteNameOffset.Value, 0); }
  public static void AddBGMName(FlatBufferBuilder builder, StringOffset BGMNameOffset) { builder.AddOffset(2, BGMNameOffset.Value, 0); }
  public static void AddTotalTime(FlatBufferBuilder builder, int TotalTime) { builder.AddInt(3, TotalTime, 0); }
  public static Offset<TShowMusicsConfigRowData> EndTShowMusicsConfigRowData(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<TShowMusicsConfigRowData>(o);
  }
};

public struct TShowMusicsConfig : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static TShowMusicsConfig GetRootAsTShowMusicsConfig(ByteBuffer _bb) { return GetRootAsTShowMusicsConfig(_bb, new TShowMusicsConfig()); }
  public static TShowMusicsConfig GetRootAsTShowMusicsConfig(ByteBuffer _bb, TShowMusicsConfig obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public TShowMusicsConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public TShowMusicsConfigRowData? Datalist(int j) { int o = __p.__offset(4); return o != 0 ? (TShowMusicsConfigRowData?)(new TShowMusicsConfigRowData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DatalistLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<TShowMusicsConfig> CreateTShowMusicsConfig(FlatBufferBuilder builder,
      VectorOffset datalistOffset = default(VectorOffset)) {
    builder.StartObject(1);
    TShowMusicsConfig.AddDatalist(builder, datalistOffset);
    return TShowMusicsConfig.EndTShowMusicsConfig(builder);
  }

  public static void StartTShowMusicsConfig(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddDatalist(FlatBufferBuilder builder, VectorOffset datalistOffset) { builder.AddOffset(0, datalistOffset.Value, 0); }
  public static VectorOffset CreateDatalistVector(FlatBufferBuilder builder, Offset<TShowMusicsConfigRowData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDatalistVectorBlock(FlatBufferBuilder builder, Offset<TShowMusicsConfigRowData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDatalistVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<TShowMusicsConfig> EndTShowMusicsConfig(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<TShowMusicsConfig>(o);
  }
};

