// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlayConditionConfigRowData struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayConditionConfigRowData(buf []byte, offset flatbuffers.UOffsetT) *PlayConditionConfigRowData {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayConditionConfigRowData{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PlayConditionConfigRowData) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayConditionConfigRowData) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayConditionConfigRowData) ID() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayConditionConfigRowData) MutateID(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *PlayConditionConfigRowData) OpenTime() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PlayConditionConfigRowData) EndTime() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PlayConditionConfigRowData) StyleCondition() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayConditionConfigRowData) MutateStyleCondition(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *PlayConditionConfigRowData) StyleNum() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PlayConditionConfigRowData) MutateStyleNum(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *PlayConditionConfigRowData) ClothesCondition() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PlayConditionConfigRowDataStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func PlayConditionConfigRowDataAddID(builder *flatbuffers.Builder, ID int32) {
	builder.PrependInt32Slot(0, ID, 0)
}
func PlayConditionConfigRowDataAddOpenTime(builder *flatbuffers.Builder, OpenTime flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(OpenTime), 0)
}
func PlayConditionConfigRowDataAddEndTime(builder *flatbuffers.Builder, EndTime flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(EndTime), 0)
}
func PlayConditionConfigRowDataAddStyleCondition(builder *flatbuffers.Builder, StyleCondition int32) {
	builder.PrependInt32Slot(3, StyleCondition, 0)
}
func PlayConditionConfigRowDataAddStyleNum(builder *flatbuffers.Builder, StyleNum int32) {
	builder.PrependInt32Slot(4, StyleNum, 0)
}
func PlayConditionConfigRowDataAddClothesCondition(builder *flatbuffers.Builder, ClothesCondition flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(ClothesCondition), 0)
}
func PlayConditionConfigRowDataEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type PlayConditionConfig struct {
	_tab flatbuffers.Table
}

func GetRootAsPlayConditionConfig(buf []byte, offset flatbuffers.UOffsetT) *PlayConditionConfig {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlayConditionConfig{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PlayConditionConfig) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlayConditionConfig) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlayConditionConfig) Datalist(obj *PlayConditionConfigRowData, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *PlayConditionConfig) DatalistLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func PlayConditionConfigStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlayConditionConfigAddDatalist(builder *flatbuffers.Builder, datalist flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(datalist), 0)
}
func PlayConditionConfigStartDatalistVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PlayConditionConfigEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
